source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'FitHub' do
    
    pod 'Moya'
    pod 'SnapKit'
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'SwiftyJSON'
    pod 'FitRefresh'
    pod 'MarkdownView'

end
